version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 4000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/echarts/home.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,golioth-websocket-datasource,volkovlabs-echarts-panel
    volumes:
      # - ./dist:/var/lib/grafana/plugins/volkovlabs-echarts-panel
      - ./provisioning:/etc/grafana/provisioning
      - ./echarts.volkovlabs.io:/etc/grafana/provisioning/dashboards/echarts
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
